### ISSUE TITLE
XSD support

### ISSUE THREAD

**Issue by romado77** [ashwinkm/Boomerang-app-support#3]
Hi Ashwin,

Any plans to introduce support of XSD?

**Comment by ashwinkm** [comment]
Hi romado77,

Boomerang already has the support for XSD files.
If your WSDL conatins any reference to the XSD files, Boomerang will automatically import it.

If you believe it is not working as expected please explain the issue here with a link to your wsdl file.
(_You can remove the private information from the wsdl if there is any, just make sure it is complete._)

Thanks.
