### ISSUE TITLE
Version 3.1.0 released and all previous settings gone!

### ISSUE THREAD

**Issue by CSADn** [ashwinkm/Boomerang-app-support#36]
Today I noticed that Boomerang app has been updated and it's not an app anymore, now it's an extension. That's cool to me because It runs inside the browser and not as a separate window.
But worst thing ever it's that all my projects, services and custom request are gone! Boomerang it's completely empty.
Is there a way to get my projects back?
Is there a way to revert the extension back again to an app to export all projects?
I'm quite sad, want you to know... 😢

**Comment by ashwinkm** [comment]
Since last 10 days Boomerang app was showing the warning message about migration and loss of data in the app.  
Most of the users had taken the backup of their data during this period.

Currently there is no way to recover your data. Boomerang extension can't access the Boomerang apps data. But data is still there. Its just extension can't see it and google webstore doesn't allow us to  revert it back to app. 

Yes, loss of data  is really sad. I feel you. In the process of migration, Boomerang lost all its users reviews on the [webstore](https://chrome.google.com/webstore/detail/boomerang-soap-rest-clien/eipdnjedkpcnlmmdfdkgfpljanehloah/reviews?hl=en).  :( . I have reported this to Chrome webstore team. But don't know what will happen.

**Comment by msrivela** [comment]
I was on vacation and when I returned I had lost everything... That was a really bad move and I just lost confidence on the app...

**Comment by bsmolyansky** [comment]
Ouch!  I'm in the same boat.  Lost all my settings.  Is there a text or JSON settings file that I can recover these values?

**Comment by xxorax** [comment]
I do not understand why did you move it from an app to an extension.

Who want his non open-source SOAP tool read all the data of his browser except careless people ?

Really bad move. I switched back to the 2.x version by downloading it [here](https://www.crx4chrome.com/crx/48838/).

**Comment by ashwinkm** [comment]
Chrome has dropped the support for apps. That means Chrome Web Store will no longer show Chrome apps and will no longer be able to load Chrome apps. More info is [here](https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html).

Even if you switch back to old version, you can use it only till browser supports apps. In future Chrome won't be loading any chrome apps.

So this migration was necessary to keep the Boomerang available for your API testing.

And about the permission, Boomerang need this permission to send data to the URL. This is a primary function of all http client.  
Any Chrome apps or extension which need access to internet resources must declare it in their manifest. Here app has requested access to all the URL (http://\*/\*) in the manifest,  so that app can send data to the URL. More info [here](https://www.howtogeek.com/291095/why-do-chrome-extensions-need-all-your-data-on-the-websites-you-visit/) and [here](https://support.google.com/chrome_webstore/answer/186213?hl=en).

**Comment by xxorax** [comment]
Oh thank, I did not know Chrome is removing App... Anyway I'm not comfortable to share chrome data with any extension.
I will try to run it with https://github.com/koush/electron-chrome

**Comment by xxorax** [comment]
Well, I finaly run it successfully (and easily) with NW.js. And this library will [continue support Chrome Apps](https://nwjs.io/blog/chrome-apps-support/).
